# Generated by Django 6.0.6 on 2026-06-15 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=6)),
                ('gateway', models.CharField(choices=[('ecocash', 'EcoCash USSD'), ('onemoney', 'OneMoney USSD'), ('innbucks', 'Innbucks Voucher'), ('paynow', 'Paynow Web Portal')], max_length=15)),
                ('reference', models.CharField(help_text='Unique invoice/system transaction reference', max_length=50, unique=True)),
                ('poll_url', models.URLField(blank=True, help_text='Internal tracking URL provided by Paynow to check status changes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Authentication'), ('success', 'Payment Confirmed'), ('failed', 'Transaction Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='listings.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('middleman', 'Agent / Broker pretending to be the Legal Owner'), ('fraud', 'Scam / Extortion / Fake contact details'), ('duplicate', 'Duplicate asset listed by multiple accounts'), ('illegal', 'Prohibited items or unlicensed commercial activity')], max_length=20)),
                ('details', models.TextField(help_text="Provide supporting evidence (e.g., 'This person asked for a viewing fee via EcoCash before showing the mill').", max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
