# Generated by Django 6.0.6 on 2026-06-15 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PROPERTY', [('house', 'House'), ('flat', 'Flat'), ('room', 'Room'), ('land', 'Land'), ('commercial', 'Commercial Building')]), ('VEHICLES', [('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle')]), ('MINING_EQUIPMENT', [('compressor', 'Compressor & Jackhammer'), ('mill_crusher', 'Ball Mill / Jaw Crusher'), ('concentrator', 'Concentrator / Gold Table'), ('pump', 'De-watering Pump'), ('detector', 'Metal Detector')]), ('GENERAL_EQUIPMENT', [('tractor', 'Tractor'), ('generator', 'Generator'), ('borehole', 'Borehole Drill'), ('construction', 'Construction Equipment'), ('agric_misc', 'Farming Equipment & Misc')])], max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('province', models.CharField(choices=[('harare', 'Harare'), ('bulawayo', 'Bulawayo'), ('manicaland', 'Manicaland'), ('mash_central', 'Mashonaland Central'), ('mash_east', 'Mashonaland East'), ('mash_west', 'Mashonaland West'), ('masvingo', 'Masvingo'), ('mat_north', 'Matabeleland North'), ('mat_south', 'Matabeleland South'), ('midlands', 'Midlands')], max_length=20)),
                ('district', models.CharField(help_text='e.g., Kadoma, Shurugwi, Gwanda, Bindura', max_length=50)),
                ('image1', models.ImageField(upload_to='listings/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/%d/')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
