# Generated by Django 6.0.6 on 2026-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_price_period',
            field=models.CharField(default='monthly', help_text='Fallback choice: daily, weekly, monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text='Local District location mapping', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email_listing_approved',
            field=models.BooleanField(default=True, help_text='Notify user upon listing compliance approval'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_new_message',
            field=models.BooleanField(default=True, help_text='Notify user upon incoming DMs'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's real full legal name", max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, help_text='Zimbabwean Province location', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone_number',
            field=models.BooleanField(default=True, help_text='Toggle raw phone visibility'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_whatsapp',
            field=models.BooleanField(default=True, help_text='Toggle click-to-chat WhatsApp communication handles'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Enable SMS broadcast updates'),
        ),
    ]
