# Generated by Django 6.0.6 on 2026-06-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalIDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_front', models.ImageField(upload_to='national_ids/front/%Y/%m/')),
                ('id_document_back', models.ImageField(blank=True, null=True, upload_to='national_ids/back/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Awaiting Administrator Review'), ('approved', 'Document Approved / Owner Verified'), ('rejected', 'Document Rejected / Invalid Identification')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Reason for rejection or verification notes.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'National ID Verification',
                'verbose_name_plural': 'National ID Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
