"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _
import os
import dj_database_url

# ==============================================================================
# 📂 BASE DIRECTORY CONFIGURATION
# ==============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# 🌐 LOCALIZATION & MULTI-LANGUAGE REGISTRY
# ==============================================================================
LANGUAGES = [
    ('en', _('English')),
    ('sn', _('Shona')),
    ('nd', _('Ndebele')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# 🔐 CORE SECURITY SETTINGS
# ==============================================================================
SECRET_KEY = 'django-insecure-(ud@7y%(g#22&pbaw(#f2@!r=6v7os6n#nn^a66x=wz6fkkqn1'
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.onrender.com', '.pythonanywhere.com']

CSRF_TRUSTED_ORIGINS = [
    'https://no-middlemen-market-1.onrender.com',
]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True

# ==============================================================================
# 📦 APPLICATION DEFINITION
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'listings',
    'payments',
    'reports',
    'messaging',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.AntiMiddlemanProtectionMiddleware',
]

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'

# ==============================================================================
# 🎨 TEMPLATE ENGINE ARCHITECTURE
# ==============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'listings.context_processors.global_platform_settings',
            ],
        },
    },
]

# ==============================================================================
# 💾 DYNAMIC AUTOMATED DUAL-DATABASE MATRIX
# ==============================================================================
DATABASES = {
    # 🛒 OPERATIONAL DATABASE: Powers users, listings, checkouts, and DMs (Falls back to SQLite locally)
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    ),
    # 📜 AUDIT & MONITORING DATABASE: Spills logs, deletions, and reports into a separate pool
    'monitoring_logs': dj_database_url.config(
        env='AUDIT_DATABASE_URL',
        default=f"sqlite:///{BASE_DIR / 'db_audit.sqlite3'}",
        conn_max_age=600
    )
}

DATABASE_ROUTERS = ['accounts.routers.AuditMonitoringRouter']

# ==============================================================================
# 👥 AUTHENTICATION CONFIGURATIONS
# ==============================================================================
AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_REDIRECT_URL = 'listings:list'
LOGOUT_REDIRECT_URL = 'listings:list'
LOGIN_URL = 'accounts:login'

# ==============================================================================
# 📁 STATIC AND MEDIA ASSETS SERVICE MANAGEMENT
# ==============================================================================
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# ✉️ COMMUNICATIONS LAYER
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'