# Generated by Django 6.0.6 on 2026-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinquiry',
            name='is_delivered',
            field=models.BooleanField(default=True),
        ),
    ]
