# Generated by Django 6.0.6 on 2026-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messageinquiry_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageinquiry',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='messageinquiry',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messageinquiry',
            name='sender',
        ),
        migrations.AddField(
            model_name='messageinquiry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
    ]
